Make settings directory follow xdg specification
chatty/chatty pull request #472
Opened 2022-07-07 05:21 UTC by yoshiyoshyosh

Would close #273

This commit changes `getUserDataDirectory` to return `$XDG_CONFIG_HOME/chatty`, or `$HOME/.config/chatty` if `$XDG_CONFIG_HOME` doesn't exist.
In addition, this commit will cause Chatty to, on startup, detect if the legacy settings directory exists ($HOME/.chatty) and, if it does, move it to whatever `getUserDataDirectory` returns. It does this on startup such that the new settings directory can be taken into effect without needing to restart the client, making for a seamless transition.

The check for the legacy directory shouldn't be in forever, obviously. I think a few versions would be enough for the majority of people to not have to wonder what happened to their settings one day whenever the check is removed.

This was tested on a Linux environment with both XDG_CONFIG_HOME set and unset. Windows environments would also get the `user.home/.chatty` directory moved to `user.home/.config/chatty`.

2023-09-05 09:08 UTC, Freso requested changes
I really like the idea of this, but I noted a couple of small issues that should probably be considered before going ahead. :)

2023-09-05 09:08 UTC, Freso commented on src/chatty/Chatty.java
> +            dir = System.getenv("XDG_CONFIG_DIR")
This should be `XDG_CONFIG_HOME`. (There is no `XDG_CONFIG_DIR` in [the specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and `XDG_CONFIG_DIRS` is not really appropriate here, though ideally that should also be searched… but that’s a whole different subject to tackle than what this PR sets out to do.)
```suggestion
        if (System.getenv("XDG_CONFIG_HOME") != null) {
            dir = System.getenv("XDG_CONFIG_HOME")
```

2023-09-05 09:12 UTC, Freso commented
> Would close #273

This only fixes the `$XDG_CONFIG_HOME` part of https://github.com/chatty/chatty/issues/273 – not the CACHE or DATA parts.

2023-09-07 01:28 UTC, yoshiyoshyosh commented
@Freso forgot that I had this pull request open--though it seems that the code surrounding the settings directory has changed a bit. I might (?) look at this again and modify it to reflect the new code, but I am very much not skilled at java, so it'd at least be a while before I sit down and rework this idea :)

2023-09-17 10:18 UTC, Freso commented
@yoshiyoshyosh Alright! I have been poking at some code to implement `$XDG_CACHE_HOME`. I can probably continue on from that work to do `$XDG_CONFIG_HOME` too. Maybe I’ll do `$XDG_DATA_HOME` too, we’ll see. :thinking:

2026-01-07 00:58 UTC, yoshiyoshyosh commented
I think someone else should pick up the torch on this--I don't have motivation to work on it myself

2026-01-07 00:58 UTC, closed without merging